### ISSUE TITLE
ブラウザ用ESモジュール化

### ISSUE THREAD

**Issue by taisukef** [2ndPINEW/HiraganaParser#23]
importの拡張子に.jsをつければ、ブラウザやDenoから直接使えるESモジュールになる！
https://github.com/2ndPINEW/HiraganaParser/commit/cc3b3fb86d7116c4abd7eae77c2c424e8f77837d

ただし、拡張子があるとテストが通らない問題あり
https://github.com/taisukef/HiraganaParser/issues/1

**Comment by 2ndPINEW** [comment]
https://github.com/2ndPINEW/HiraganaParser/pull/28 で標準ESMにして https://github.com/2ndPINEW/HiraganaParser/pull/29 で cloudflare 経由でデプロイするようにしました~
