### ISSUE TITLE
MITライセンスの記述が見当たりませんでした。

### ISSUE THREAD

**Issue by ir255bus** [2ndPINEW/HiraganaParser#34]
NPMやpackage.jsonにはMITライセンスと書かれてあったので、制約に基づいて自分のプロジェクトに著作権表示しようと思ったのですが、MITライセンスの記述が見当たりませんでした。どのように表示すれば良いでしょうか？

初心者なので見当違いなことを言っていたらすみません。

**Comment by 2ndPINEW** [comment]
すみません、書きました！
https://github.com/2ndPINEW/HiraganaParser/pull/35

**Comment by ir255bus** [comment]
ありがとうございます！

**Comment by 2ndPINEW** [comment]
指摘助かりました！    
こちらこそありがとうございます！
